--[[---------------------------------------------------------------------------
	File              : pda_hack.script
	Description       : Сниманм деньги с КПК мервых сталкеров
	Created           : 29.11.2014
	Copyright         : naxac
	Last edited		  : Dancher
--]]---------------------------------------------------------------------------

-- Звуки нотификации
pda_news = xr_sound.get_safe_sound_object([[device\pda\pda_news]])

local npc_community = 
{
	["stalker"] = "одиночки",
	["monolith"] = "монолитовца",
	["military"] = "военного",
	["bandit"] = "бандита",
	["killer"] = "наемника",
	["ecolog"] = "учёного",
	["dolg"] = "долговца",
	["freedom"] = "свободовца",
	["zombied"] = "зомбированного",
	["trader"] = "торговеца",
	["arena_enemy"] = "сталкера",
	["actor"] = "одиночки",
	["actor_dolg"] = "долговца", 
	["actor_freedom"] = "свободовца"
}

function use_pda(obj)
	-- Читаем данные из нет_пэкета
	local sobj = alife():object(obj:id())
	local tbl = pda_hack.get_item_data(sobj)
	local str = tbl.custom
	if str == nil or string.len(tostring(str)) == 0 then
		news_manager.send_tip(db.actor, "pda_hack: ERROR!!! Custom data is absent!")
		return
	end
	
	-- Распарсиваем строку в таблицу
	local p = {}
	for a in string.gmatch(str, "[_%w]+") do
		table.insert(p,a)
	end
	
	local name = p[1]~=nil and tostring(p[1]) or "ytbpdtcnysq"
	name = convert_string(name, "torus")	-- раскодируем строку обратно в кириллицу
	local community = p[2]~=nil and tostring(p[2]) or "stalker"
	local rank = tonumber(p[3]) or 0
	
	local deadmoney = 0
	local deadmoney_amount_color = "%c[default]"

	if pda_upgrade_manager.has_upgrade(1) then
		deadmoney = pda_upgrade_manager.use_upgrade(1, rank)
		--deadmoney_amount_color = "%c[255,12,150,12]"
	else
		deadmoney = get_money_standart(rank)
	end
	
	db.actor:give_money(deadmoney)
	
	show_notification(deadmoney, community, name, deadmoney_amount_color)
end

function create_pda_npc(npc, pda)
	local str = convert_string(npc:character_name(), "toeng")..","..
				npc:character_community()..","..
				tostring(npc:character_rank())
	-- Запишем все данные о владельце КПК в нет_пэкет КПК
	local sobj = alife():create("pda_npc",vector(),0,0,npc:id())
	local tbl = pda_hack.get_item_data(sobj)
	tbl.custom = str
	pda_hack.set_item_data(tbl,sobj)
end

-- Перекодируем строку в латиницу, т.к. кириллицу сталкерский двиг не переваривает
local lat = [[qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM_1234567890]]
local rus = [[йцукенгшщзфывапролдячсмитьЙЦУКЕНГШЩЗФЫВАПРОЛДЯЧСМИТХ жэхъбюЖЭБЮ]]	-- 'Ь' и 'Ъ', думаю, не нужны)
function convert_string(str, mode)
	if str==nil or #str == 0 then return end
	local ret = ""
	if mode=="toeng" then
		str = string.gsub(str,"ё","е")
		str = string.gsub(str,"Ё","Е")
	end
	local s1 = mode=="toeng" and rus or lat
	local s2 = mode=="toeng" and lat or rus
	for i=1,#str do
		local l = string.sub(str,i,i)
		local p = string.find(s1,l,1,true)
		ret = ret..(p~=nil and string.sub(s2,p,p) or "_")
	end
	return ret
end


function show_notification(money_amount, community, name, money_amount_color)
	local title = "%c[255,160,160,160]КПК "..npc_community[community].." ("..name.."):"

	local message = "%c[default]Обнаружено "..money_amount_color..tostring(money_amount).."%c[default] руб."
	local news_text = title.."\\n"..message

	local task_texture, task_rect = get_texture_info("ui_iconsTotal_found_money")
	
	db.actor:give_game_news(news_text, task_texture, task_rect, 0, 3000)
	pda_news:play(db.actor, 0, sound_object.s2d)
end

function get_money_standart(rank)
	local deadmoney = 0
	
    if rank<300 then 
		deadmoney=math.random(36,75)    -- novice
    elseif rank<600 then 
		deadmoney=math.random(75,150)    -- experienced
    elseif rank<900 then 
		deadmoney=math.random(150,250)        -- veteran
    elseif rank>=900 then 
		deadmoney=math.random(250,500)		-- master
	end    
	
	return deadmoney
end
----------------------------------------------------------------------------------
-- Функции для работы с нет_пэкетами (АМК)
function get_item_data(sobj)
	local stpk=net_packet()
	local uppk=net_packet()
	sobj:STATE_Write(stpk)
	sobj:UPDATE_Write(uppk)
	local size=stpk:w_tell()
	local size1=uppk:w_tell()
	stpk:r_seek(0)
	uppk:r_seek(0)
	local t={}
	pda_hack.parse_object_packet(t,stpk,uppk,size)
	pda_hack.parse_visual_packet(t,stpk,uppk,size)
	pda_hack.parse_item_packet(t,stpk,uppk,size)
	return t
end

function set_item_data(t,sobj)
	local stpk=net_packet()
	local uppk=net_packet()
	
	pda_hack.fill_object_packet(t,stpk,uppk)
	pda_hack.fill_visual_packet(t,stpk,uppk)
	pda_hack.fill_item_packet(t,stpk,uppk)
	
	local size=stpk:w_tell()
	local size1=uppk:w_tell()
	stpk:r_seek(0)
	uppk:r_seek(0)
	sobj:STATE_Read(stpk,size)
	sobj:UPDATE_Read(uppk)
end

function parse_object_packet(ret,stpk,updpk)
	ret.gvid=stpk:r_u16()
	ret.obf32u1=stpk:r_float()
	ret.obs32u2=stpk:r_s32()
	ret.lvid=stpk:r_s32()
	ret.oflags=stpk:r_s32()
	ret.custom=stpk:r_stringZ()
	ret.sid=stpk:r_s32()
	ret.obs32u3=stpk:r_s32()
	return ret
end

function parse_visual_packet(ret,stpk,updpk)
	ret.visual=stpk:r_stringZ()
	ret.vsu8u1=stpk:r_u8()
	return ret
end

function fill_object_packet(ret,stpk,updpk)
	stpk:w_u16(ret.gvid)
	stpk:w_float(ret.obf32u1)
	stpk:w_s32(ret.obs32u2)
	stpk:w_s32(ret.lvid)
	stpk:w_s32(ret.oflags)
	stpk:w_stringZ(ret.custom)
	stpk:w_s32(ret.sid)
	stpk:w_s32(ret.obs32u3)
end

function fill_visual_packet(ret,stpk,updpk)
	stpk:w_stringZ(ret.visual)
	stpk:w_u8(ret.vsu8u1)
end

function parse_item_packet(ret,stpk,updpk)
  ret.condition=stpk:r_float()
  ret.updnum_items=updpk:r_u8()
  return ret
end

function fill_item_packet(ret,stpk,updpk)
  stpk:w_float(ret.condition)
  updpk:w_u8(ret.updnum_items)
  return ret
end